# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque-timeout}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Gran"]
  s.date = %q{2011-03-07}
  s.description = %q{Resque plugin allowing long-running jobs to automatically fail after a specified time.}
  s.email = %q{jeff.gran@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/resque-timeout.rb",
    "lib/resque/plugins/timeout.rb",
    "resque-timeout.gemspec",
    "spec/resque-timeout_spec.rb",
    "spec/resque/plugins/timeout_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jeffgran/resque-timeout}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Timeout for long-running jobs in Resque}
  s.test_files = [
    "spec/resque-timeout_spec.rb",
    "spec/resque/plugins/timeout_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<resque>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<resque>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

